interface RewrittenCopy {
  headline: string;
  subheadline: string;
  problem_section: string[];
  primary_cta: string;
  testimonial_suggestions: string[];
}

interface FullAnalysis {
  rewritten_copy: RewrittenCopy;
}

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

export function generateHtmlTemplate(url: string, analysis: FullAnalysis): string {
  const copy = analysis.rewritten_copy;
  const year = new Date().getFullYear();

  const problemCards = copy.problem_section
    .map(
      (pain, i) => `
      <!-- Pain point ${i + 1} — edit the text if needed but keep it specific -->
      <div class="rounded-2xl bg-slate-50 border border-slate-200 p-6">
        <div class="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center mb-4">
          <span class="text-blue-600 font-black text-lg">${i + 1}</span>
        </div>
        <p class="text-slate-700 font-medium leading-relaxed">${esc(pain)}</p>
      </div>`
    )
    .join("\n");

  const testimonialCards = copy.testimonial_suggestions
    .map(
      (suggestion, i) => `
      <!-- ============================================================
           TESTIMONIAL ${i + 1} — REPLACE BEFORE GOING LIVE

           How to get this testimonial:
           Contact one of your best customers and ask them:
           "${suggestion}"

           Then paste their exact answer as the quote text below.
           Use their real name — it builds far more trust than initials.
           ============================================================ -->
      <div class="rounded-2xl bg-white border border-slate-200 p-6 shadow-sm">
        <div class="flex gap-0.5 mb-4">
          <span class="text-blue-500 text-base">★</span>
          <span class="text-blue-500 text-base">★</span>
          <span class="text-blue-500 text-base">★</span>
          <span class="text-blue-500 text-base">★</span>
          <span class="text-blue-500 text-base">★</span>
        </div>
        <p class="text-slate-700 mb-5 leading-relaxed italic text-sm">
          <!-- REPLACE: Paste your customer's actual quote here.
               Ask them: "${esc(suggestion)}" -->
          "REPLACE: Paste your customer's answer to this question here — '${esc(suggestion)}'"
        </p>
        <div>
          <!-- REPLACE: Customer's real name and location or project type -->
          <p class="font-semibold text-slate-900 text-sm">REPLACE: Customer Name</p>
          <p class="text-slate-400 text-xs mt-0.5">REPLACE: Town or project type (e.g. "Bathroom renovation, Bath")</p>
        </div>
      </div>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<!-- ================================================================
     HOMEPAGE — Generated by GradeMysite
     Source URL: ${esc(url)}

     DEVELOPER HANDOFF NOTES:

     This file is a complete, self-contained homepage. To use it:
     1. Replace all "REPLACE:" placeholders with real content
     2. Replace the hero image placeholder with a real photo
     3. Add real testimonials before going live
     4. Update all links (#contact, #pricing) to point to real pages
        or anchor IDs, then adjust as needed
     5. Remove Tailwind CDN and replace with a proper build step
        for production performance (optional but recommended)

     The business owner will brief you on prices and contact details.
     Everything else is ready — copy, structure, and styling.
     ================================================================ -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- REPLACE: Change the title to your business name + main service -->
  <title>REPLACE: Your Business Name — ${esc(copy.headline)}</title>
  <meta name="description" content="${esc(copy.subheadline)}">
  <!-- Tailwind CSS via CDN — works out of the box, no build step needed -->
  <script src="https://cdn.tailwindcss.com"></script>
  <style>
    html { scroll-behavior: smooth; }
    /* Remove CDN warning banner that Tailwind shows in development */
    .tailwind-warning { display: none !important; }
  </style>
</head>
<body class="font-sans antialiased text-slate-900 bg-white">

<!-- ============================================================
     HEADER

     What to change:
     - "Your Business Name" → your actual business name or logo image
     - The CTA button href → your phone (tel:01234 567890), email
       (mailto:hello@you.co.uk), or a contact form anchor (#contact)
     - The button text is already set to your best CTA copy
     ============================================================ -->
<header class="sticky top-0 z-50 bg-slate-900 shadow-lg">
  <div class="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">

    <!-- REPLACE: Your business name — or swap for an <img> logo tag -->
    <a href="#" class="text-xl font-black text-white tracking-tight">
      Your Business Name
    </a>

    <nav class="flex items-center gap-6">
      <a
        href="#pricing"
        class="text-sm font-medium text-slate-300 hover:text-white transition-colors hidden sm:block"
      >
        Pricing
      </a>
      <!-- REPLACE: Update href to your phone, email, or booking link -->
      <a
        href="#contact"
        class="bg-blue-600 hover:bg-blue-700 text-white text-sm font-semibold px-5 py-2.5 rounded-lg transition-colors"
      >
        ${esc(copy.primary_cta)}
      </a>
    </nav>

  </div>
</header>


<!-- ============================================================
     HERO

     This is the most important section — most visitors will only
     read this far. The headline and subheadline were written
     specifically for your business. Keep them as-is unless you
     have a strong reason to change.

     What to change:
     - The hero image placeholder (see the comment inside)
     - The CTA button href (same as the header)
     ============================================================ -->
<section class="bg-slate-900 text-white py-20 sm:py-28 px-6">
  <div class="max-w-4xl mx-auto text-center">

    <!-- Headline — do not dilute this, specificity is what makes it work -->
    <h1 class="text-4xl sm:text-5xl lg:text-6xl font-black leading-tight tracking-tight mb-6">
      ${esc(copy.headline)}
    </h1>

    <!-- Subheadline — contains a specific number, keep that in -->
    <p class="text-xl sm:text-2xl text-slate-300 leading-relaxed mb-10 max-w-2xl mx-auto">
      ${esc(copy.subheadline)}
    </p>

    <!-- Primary CTA — this should be the only button above the fold -->
    <!-- REPLACE: Update href to your phone, email, or booking form -->
    <a
      href="#contact"
      class="inline-block bg-blue-600 hover:bg-blue-700 text-white text-lg font-bold px-8 py-4 rounded-xl transition-colors shadow-lg shadow-blue-600/25"
    >
      ${esc(copy.primary_cta)}
    </a>

    <!-- ============================================================
         HERO IMAGE — REPLACE THIS BEFORE GOING LIVE

         The image placeholder below must be replaced with a real photo
         showing your actual completed work. Stock images convert poorly.

         Recommended: your single best "before and after" or finished
         project photo. Size: at least 1200×600px.

         To replace: delete the entire <div class="mt-16 ..."> block
         below and replace with:

         <img
           src="your-hero-photo.jpg"
           alt="REPLACE: Description of the project shown"
           class="mt-16 w-full rounded-2xl shadow-2xl object-cover"
           style="max-height:480px"
         >
         ============================================================ -->
    <div class="mt-16 rounded-2xl border-2 border-dashed border-slate-600 bg-slate-800 h-64 sm:h-80 flex flex-col items-center justify-center gap-3 text-slate-500">
      <svg class="w-12 h-12 opacity-40" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
      </svg>
      <p class="text-sm font-semibold">REPLACE: Add your best project photo here</p>
      <p class="text-xs text-slate-600 max-w-xs text-center">Show completed work — real photos convert far better than stock images</p>
    </div>

  </div>
</section>


<!-- ============================================================
     PROBLEM SECTION

     These pain points were written specifically for your customers.
     They should feel like you're reading their mind — that's the
     point. Don't soften them. Specificity is what makes people feel
     understood.

     What to change: nothing, unless a pain point doesn't fit.
     ============================================================ -->
<section class="bg-white py-20 sm:py-24 px-6">
  <div class="max-w-4xl mx-auto">

    <div class="text-center mb-12">
      <p class="text-blue-600 font-semibold text-sm uppercase tracking-wider mb-3">Sound familiar?</p>
      <h2 class="text-3xl sm:text-4xl font-black text-slate-900 leading-tight">
        You know your work is good.<br class="hidden sm:block">
        Your website doesn't show it.
      </h2>
    </div>

    <div class="grid sm:grid-cols-3 gap-6">
      ${problemCards}
    </div>

  </div>
</section>


<!-- ============================================================
     SOLUTION SECTION

     This is where you introduce your service — clearly, once.
     The copy is already written. Add your key selling points in
     the checklist on the right side.

     What to change:
     - The three "REPLACE" items in the checklist
     - The CTA href (same as header)
     ============================================================ -->
<section class="bg-slate-900 text-white py-20 sm:py-24 px-6">
  <div class="max-w-4xl mx-auto">
    <div class="grid sm:grid-cols-2 gap-12 items-center">

      <div>
        <p class="text-blue-500 font-semibold text-sm uppercase tracking-wider mb-3">The solution</p>
        <h2 class="text-3xl sm:text-4xl font-black text-white leading-tight mb-5">
          ${esc(copy.headline)}
        </h2>
        <p class="text-slate-300 text-lg leading-relaxed mb-8">
          ${esc(copy.subheadline)}
        </p>
        <!-- REPLACE: Update href to your booking/contact link -->
        <a
          href="#contact"
          class="inline-block bg-blue-600 hover:bg-blue-700 text-white font-bold px-7 py-3.5 rounded-xl transition-colors"
        >
          ${esc(copy.primary_cta)}
        </a>
      </div>

      <!-- REPLACE: Fill in your 3 main selling points or process steps.
           These should answer "why you, not a competitor?" -->
      <div class="rounded-2xl bg-white/5 border border-white/10 p-8">
        <p class="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-5">Why customers choose us</p>
        <ul class="space-y-4">
          <li class="flex items-start gap-3 text-slate-300">
            <span class="text-blue-500 font-bold mt-0.5 flex-shrink-0">✓</span>
            <!-- REPLACE: Your first key benefit — e.g. "Fixed-price quotes with no hidden extras" -->
            <span>REPLACE: Your first key differentiator or benefit</span>
          </li>
          <li class="flex items-start gap-3 text-slate-300">
            <span class="text-blue-500 font-bold mt-0.5 flex-shrink-0">✓</span>
            <!-- REPLACE: Your second key benefit — something specific to your business -->
            <span>REPLACE: Your second key differentiator or benefit</span>
          </li>
          <li class="flex items-start gap-3 text-slate-300">
            <span class="text-blue-500 font-bold mt-0.5 flex-shrink-0">✓</span>
            <!-- REPLACE: What happens after the customer contacts you -->
            <span>REPLACE: What happens next after a customer gets in touch</span>
          </li>
        </ul>
      </div>

    </div>
  </div>
</section>


<!-- ============================================================
     SOCIAL PROOF

     REPLACE ALL THREE TESTIMONIALS before the site goes live.

     How to collect these testimonials:
     For each slot, contact one of your best customers and ask them
     the exact question shown in the HTML comment above that slot.
     Copy their exact words — don't paraphrase.

     Real quotes, even short ones, outperform polished fake-sounding
     ones every time.
     ============================================================ -->
<section class="bg-slate-50 py-20 sm:py-24 px-6">
  <div class="max-w-4xl mx-auto">

    <div class="text-center mb-12">
      <p class="text-blue-600 font-semibold text-sm uppercase tracking-wider mb-3">What customers say</p>
      <h2 class="text-3xl sm:text-4xl font-black text-slate-900">Real results, real people</h2>
    </div>

    <div class="grid sm:grid-cols-3 gap-6">
      ${testimonialCards}
    </div>

  </div>
</section>


<!-- ============================================================
     PRICING

     REPLACE: Add your actual service tiers and prices here.

     The Good/Better/Best structure is intentional — it anchors
     value and makes the middle tier feel like the smart choice.
     Most customers will pick "Better".

     Tips:
     - Name the tiers after what the customer gets, not what
       you do (e.g. "Peace of Mind" not "Full Service Package")
     - The Most Popular badge goes on your most profitable tier
     - Add a "from £X" line if your pricing varies by job
     ============================================================ -->
<section id="pricing" class="bg-white py-20 sm:py-24 px-6">
  <div class="max-w-4xl mx-auto">

    <div class="text-center mb-12">
      <p class="text-blue-600 font-semibold text-sm uppercase tracking-wider mb-3">Pricing</p>
      <h2 class="text-3xl sm:text-4xl font-black text-slate-900 mb-3">Simple, transparent pricing</h2>
      <!-- REPLACE: Describe your pricing model in one line -->
      <p class="text-slate-500 max-w-md mx-auto text-sm">
        REPLACE: e.g. "Fixed price. No hidden extras. Written quote before any work starts."
      </p>
    </div>

    <div class="grid sm:grid-cols-3 gap-6">

      <!-- TIER 1: GOOD -->
      <!-- REPLACE: Rename to your entry-level package name -->
      <div class="rounded-2xl border border-slate-200 bg-white p-7 flex flex-col">
        <div class="mb-5">
          <p class="font-bold text-slate-900 text-base mb-1">Good</p>
          <!-- REPLACE: One sentence about who this tier is for -->
          <p class="text-slate-500 text-sm">REPLACE: Ideal for [type of customer]</p>
        </div>
        <div class="mb-6">
          <!-- REPLACE: Your price -->
          <span class="text-4xl font-black text-slate-900">£0</span>
          <!-- REPLACE: Pricing unit — e.g. "/job", "from", "/month" -->
          <span class="text-slate-400 text-sm ml-1">REPLACE</span>
        </div>
        <ul class="space-y-2.5 text-sm text-slate-600 flex-1 mb-7">
          <!-- REPLACE: Add 3–4 bullet points for this package -->
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Feature 1</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Feature 2</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Feature 3</li>
        </ul>
        <!-- REPLACE: Update href to your booking/contact link -->
        <a href="#contact" class="block w-full py-3 rounded-xl border border-slate-200 text-slate-700 font-semibold text-sm text-center hover:bg-slate-50 transition-colors">
          ${esc(copy.primary_cta)}
        </a>
      </div>

      <!-- TIER 2: BETTER (MOST POPULAR) -->
      <!-- REPLACE: Rename to your mid-tier package name. This is the one to highlight. -->
      <div class="rounded-2xl border-2 border-blue-600 bg-white p-7 flex flex-col relative mt-4 sm:mt-0">
        <div class="absolute -top-4 left-1/2 -translate-x-1/2">
          <span class="bg-blue-600 text-white text-xs font-bold px-3 py-1 rounded-full whitespace-nowrap">MOST POPULAR</span>
        </div>
        <div class="mb-5">
          <p class="font-bold text-slate-900 text-base mb-1">Better</p>
          <!-- REPLACE: One sentence about who this tier is for -->
          <p class="text-slate-500 text-sm">REPLACE: Ideal for [type of customer]</p>
        </div>
        <div class="mb-6">
          <!-- REPLACE: Your price -->
          <span class="text-4xl font-black text-slate-900">£0</span>
          <!-- REPLACE: Pricing unit -->
          <span class="text-slate-400 text-sm ml-1">REPLACE</span>
        </div>
        <ul class="space-y-2.5 text-sm text-slate-600 flex-1 mb-7">
          <!-- REPLACE: Add 4–5 bullet points — include everything from Good, plus extras -->
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Everything in Good</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Key extra feature 1</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Key extra feature 2</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Key extra feature 3</li>
        </ul>
        <!-- REPLACE: Update href to your booking/contact link -->
        <a href="#contact" class="block w-full py-3 rounded-xl bg-blue-600 hover:bg-blue-700 text-white font-semibold text-sm text-center transition-colors">
          ${esc(copy.primary_cta)}
        </a>
      </div>

      <!-- TIER 3: BEST -->
      <!-- REPLACE: Rename to your premium package name -->
      <div class="rounded-2xl border border-slate-200 bg-white p-7 flex flex-col">
        <div class="mb-5">
          <p class="font-bold text-slate-900 text-base mb-1">Best</p>
          <!-- REPLACE: One sentence about who this tier is for -->
          <p class="text-slate-500 text-sm">REPLACE: Ideal for [type of customer]</p>
        </div>
        <div class="mb-6">
          <!-- REPLACE: Your price -->
          <span class="text-4xl font-black text-slate-900">£0</span>
          <!-- REPLACE: Pricing unit -->
          <span class="text-slate-400 text-sm ml-1">REPLACE</span>
        </div>
        <ul class="space-y-2.5 text-sm text-slate-600 flex-1 mb-7">
          <!-- REPLACE: Add 5+ bullet points — include everything from Better, plus premium extras -->
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Everything in Better</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Premium extra 1</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Premium extra 2</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Premium extra 3</li>
          <li class="flex items-start gap-2"><span class="text-emerald-500 font-bold flex-shrink-0 mt-0.5">✓</span> REPLACE: Premium extra 4</li>
        </ul>
        <!-- REPLACE: Update href to your booking/contact link -->
        <a href="#contact" class="block w-full py-3 rounded-xl border border-slate-200 text-slate-700 font-semibold text-sm text-center hover:bg-slate-50 transition-colors">
          ${esc(copy.primary_cta)}
        </a>
      </div>

    </div>

    <!-- REPLACE: Add a pricing guarantee, payment terms, or trust note -->
    <p class="text-center text-slate-400 text-sm mt-8">
      REPLACE: e.g. "Fixed price. Written quote before any work begins. 7-day money-back guarantee."
    </p>

  </div>
</section>


<!-- ============================================================
     FOOTER CTA

     One last push. Keep this simple — just the CTA.
     This section also contains the contact anchor (#contact)
     which all the buttons on this page point to.

     What to change:
     - The CTA button href to your actual phone/email/booking link
     - The contact info line at the bottom
     ============================================================ -->
<section id="contact" class="bg-slate-900 text-white py-20 sm:py-28 px-6">
  <div class="max-w-xl mx-auto text-center">

    <h2 class="text-3xl sm:text-4xl font-black mb-5">Ready to get started?</h2>
    <p class="text-slate-300 text-lg leading-relaxed mb-10">
      ${esc(copy.subheadline)}
    </p>

    <!-- REPLACE: Update href to your phone (tel:01234567890), email (mailto:), or booking page -->
    <a
      href="#"
      class="inline-block bg-blue-600 hover:bg-blue-700 text-white text-xl font-bold px-10 py-5 rounded-2xl transition-colors shadow-xl shadow-blue-600/20"
    >
      ${esc(copy.primary_cta)}
    </a>

    <!-- REPLACE: Your phone number, email, or both -->
    <p class="text-slate-500 text-sm mt-10">
      REPLACE: Your phone number · REPLACE: hello@yourbusiness.co.uk
    </p>

  </div>
</section>

<!-- FOOTER -->
<footer class="bg-slate-950 text-slate-500 py-8 px-6">
  <div class="max-w-5xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4 text-sm">
    <!-- REPLACE: Your business name -->
    <span class="font-bold text-slate-300">Your Business Name</span>
    <div class="flex flex-col sm:flex-row items-center gap-3 sm:gap-6 text-xs">
      <!-- REPLACE: Your website and email -->
      <span>REPLACE: yoursite.co.uk</span>
      <span class="hidden sm:block">·</span>
      <span>REPLACE: hello@yoursite.co.uk</span>
      <span class="hidden sm:block">·</span>
      <span>© ${year}</span>
    </div>
  </div>
</footer>

</body>
</html>`;
}
